# Generated by Django 6.0.4 on 2026-04-27 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activationtoken',
            options={'verbose_name': 'Activation Token', 'verbose_name_plural': 'Activation Tokens'},
        ),
        migrations.AlterModelOptions(
            name='passwordresettoken',
            options={'verbose_name': 'Password Reset Token', 'verbose_name_plural': 'Password Reset Tokens'},
        ),
    ]
