# Generated by Django 6.0.4 on 2026-04-23 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='Gibt an, ob Video für HLS verarbeitet wurde'),
        ),
        migrations.CreateModel(
            name='VideoResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(choices=[('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], max_length=10)),
                ('hls_playlist', models.FileField(blank=True, null=True, upload_to='videos/hls/')),
                ('file_size', models.BigIntegerField(default=0, help_text='Dateigröße in Bytes')),
                ('is_ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='content.video')),
            ],
            options={
                'verbose_name': 'Video-Auflösung',
                'verbose_name_plural': 'Video-Auflösungen',
                'unique_together': {('video', 'resolution')},
            },
        ),
    ]
