# Generated by Django 6.0.4 on 2026-04-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_video_is_processed_videoresolution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='videoresolution',
            options={'verbose_name': 'Video Resolution', 'verbose_name_plural': 'Video Resolutions'},
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='Indicates if video has been processed for HLS'),
        ),
        migrations.AlterField(
            model_name='videoresolution',
            name='file_size',
            field=models.BigIntegerField(default=0, help_text='File size in bytes'),
        ),
    ]
